### ISSUE TITLE
Provide documentation and screenshots on github.io

### ISSUE THREAD

**Issue by friedger** [gdg-x/boomerang#4]

**Comment by Splaktar** [comment]
The cook-book type guide should already be there in the README.md. Please let me know if there are updates you would like to see.

I've added the gh-pages branch for github.io hosting. This can be seen here: http://gdg-x.github.io/boomerang 

I will update the README to include this link.

**Comment by Splaktar** [comment]
Closed via 4d0564f54d5ff7b745f54fd880ba1fed2e1e8866
