### ISSUE TITLE
Include demo or users of the project

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/boomerang#40]
In the README, it would be great if you can include GDGs and their webpage addresses that uses this project.

**Comment by Splaktar** [comment]
Demo site that uses this project done via 4d0564f54d5ff7b745f54fd880ba1fed2e1e8866

**Comment by Splaktar** [comment]
Started a list of sites that use this template in 20657e97cf74cecd2231fee2758a6e5ce9102e93
Please send a pull request to add your site to the list.
