### ISSUE TITLE
Add a 'What We Do' type page

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/boomerang#46]
It should describe the kind of events that the chapter runs. The event types should be configurable via the ConfigService. This allows a chapter who does not run Hackathons to remove that listing from their page.

Some of the event types that should be described are:

* Tech Talks
* Code Labs
* Hackathons
* App Clinics
* Design Sprints
* Round Tables

**Comment by friedger** [comment]
Good, but instead of configuring the ConfigService, it would be better to have the data hosted on the hub. Still the UI needs to be added here.

**Comment by Splaktar** [comment]
I agree that moving some of these settings to the Hub for longer term persistence would be great. But the Hub will need that feature before we can take advantage of it. Perhaps just an API for a chapter to specify an 'options' JSON object which could contain settings like this would be enough.

For now, I think that it will go in the ConfigService until the Hub can support this. We should open an issue in the Hub for this.

I am working on this "What We Do" feature atm.

**Comment by Splaktar** [comment]
![screen shot 2015-05-24 at 6 54 19 pm](https://cloud.githubusercontent.com/assets/3506071/7790745/5b6a84e0-0246-11e5-87e2-485de0c0f790.png)

Here is an example of what this will look like.

**Comment by Splaktar** [comment]
This is done in boomerang-gae. Will merge it over here after dinner.

**Comment by tasomaniac** [comment]
Wow. You are great. :+1: 
It looks really good.
