### ISSUE TITLE
Add integration with Firefly

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/boomerang#47]
Offer some kind of way for members to access the different Firefly listings like angularjs, android, wtm, etc and provide links to the different Firefly sites (gdg.events). 

This could perhaps go under a Global Events tab. I'm not sure if the current events tab will need to be renamed to 'Local Events' or 'Chapter Events' but it should be considered.

**Comment by friedger** [comment]
Single events have a page on the gdg.events as well, like http://gdg.events/6330124294160384/ So one could add a link, or is this just about event series? Add a link from a tag of an event to the corresponding tag.gdg.events page?

**Comment by Splaktar** [comment]
Yes, we should try to figure out how to add links to the events in Firefly as well. That should probably be tracked in a separate issue though.
