### ISSUE TITLE
Add config for organizer list

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/boomerang#49]
Add an array of Google+ Ids to ConfigService that can be used to pull profile pictures, links, tagline, and description for display on a list of organizer cards.

**Comment by tasomaniac** [comment]
I believe those can be retrieved from developers.google.com site or GDG[X] Hub API.

**Comment by friedger** [comment]
http://hub.gdgx.io/api/v1/chapters/105068877693379070381 contains the ids of the organizers

**Comment by tasomaniac** [comment]
Exactly. :)

**Comment by Splaktar** [comment]
Yep, this should be easy to get from the existing code in the Hub's front-end as well.

**Comment by Splaktar** [comment]
This is done in boomerang-gae. Will merge it here today.
