### ISSUE TITLE
Add Footer with link to GitHub, etc similar to Firefly

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/boomerang#59]

**Comment by SaptakS** [comment]
What exactly do we need to do in this issue?

**Comment by Splaktar** [comment]
Here's firefly's footer : https://github.com/gdg-x/firefly/tree/master/client/components/footer

You can see it in action here: http://gdgroups.org

**Comment by SaptakS** [comment]
Ok. I will work on it asap.

**Comment by Splaktar** [comment]
@SaptakS any questions about this? Please let me know if I can help in any way.

**Comment by SaptakS** [comment]
#98 
Sorry for the delay. Busy with Google Summer of Code. :smiley:

**Comment by Splaktar** [comment]
Awesome. Thank you! No problem for the delay, everyone gets busy.

**Comment by Splaktar** [comment]
Closed by https://github.com/gdg-x/boomerang/commit/dcc7d438aa923dae766cd59a9d0dfa29e0a6b5d9.
