### ISSUE TITLE
Add Icon and link config for YouTube

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/boomerang#61]
Allow chapters to easily link to YouTube channel.

**Comment by SaptakS** [comment]
I would like to work on this issue.

**Comment by Splaktar** [comment]
Awesome. I will try to review soon. Prepping for a Meetup tomorrow though.

**Comment by SaptakS** [comment]
Ok.. cool.

**Comment by Splaktar** [comment]
@SaptakS Thanks a lot!
