### ISSUE TITLE
Add Code of Conduct page

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/boomerang#62]
See http://dev.gdgtc.com/gdgtc-site-polymer/#conduct for example.

**Comment by SaptakS** [comment]
Would like to contribute in this enhancement. Should the content for the code of conduct page be the same as the one given in the above link?

**Comment by friedger** [comment]
@SaptakS Actually, there is the http://github.com/gdg-x/code_of_conduct/ 

So this issue is about adding a link to the contributing page, similar to https://github.com/gdg-x/frisbee

**Comment by SaptakS** [comment]
But the [code of conduct page](http://github.com/gdg-x/code_of_conduct/) is in .md format. So even if we give the link, it won't appear as an HTML page. Correct me if I am wrong or if I understood something wrong..

**Comment by friedger** [comment]
That is good enough:
https://github.com/gdg-x/code_of_conduct/blob/master/CONTRIBUTING.md



[image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2016-02-23 13:01 GMT+01:00 Saptak Sengupta <notifications@github.com>:

**Comment by SaptakS** [comment]
Ok.

**Comment by Splaktar** [comment]
Actually, this issue is about having a real HTML COC page in the boomerang app. So no, a link to github is not enough. 

What Friedger is referring to is a separate issue.

**Comment by Splaktar** [comment]
As for content, the COC content from the link mentioned is for GDG-X. The COC content that should be displayed in boomerang should be the GDG COC. 

We should also include the values statement as well. Here it is :
GDG [insert Chapter Name] is an inclusive community where developers, designers, and entrepreneurs of all skill levels, genders, religions, and backgrounds are welcome to learn, practice, and share Google technologies, services, and platforms. Our motto is “Be excellent to each other;” if you see or experience anything different please contact [name of GDG lead]

**Comment by SaptakS** [comment]
Ok. Will start work on this asap.

**Comment by Splaktar** [comment]
OK, as for the actual messaging of the CoC, I don't have a final version of it yet.

I think that the [GDG Community Guidelines](https://developers.google.com/groups/guidelines/) are too focused on GDG Organizer things like the mailing list.

Other examples:
http://www.meetup.com/seattle-gdg/pages/Code_of_Conduct/
http://gdggigcity.com/coc
http://dev.gdgtc.com/gdgtc-site-polymer/#conduct
http://gdg-dublin.appspot.com/#!/code-of-conduct

**Comment by SaptakS** [comment]
Should I provide a new object in the `configService.js` file to edit the content of Code of Conduct? Then, each community can edit the content they want to display on their respect code of conduct page.

**Comment by Splaktar** [comment]
I would rather not put that much text into the configService. If a chapter wanted to customize it, I don't think modifying the template is too bad.

**Comment by SaptakS** [comment]
Ok.

**Comment by SaptakS** [comment]
Fixed in #79
