### ISSUE TITLE
Remove # of Shares link from News page now that Ripples were removed from G+

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/boomerang#70]
This currently just takes you to the Google 404 page:

    404. That’s an error.

    The requested URL was not found on this server. That’s all we know.

**Comment by Splaktar** [comment]
Going to just disable the button rather than remove it since we do have the number of shares, similar to the number of comments and plus ones. We just can't link directly into a post's activity display anymore. It's only accessible from the Google+ app manually.

**Comment by tasomaniac** [comment]
:+1:
