### ISSUE TITLE
$injector:modulerr error

### ISSUE THREAD

**Issue by SaptakS** [gdg-x/boomerang#88]
I copied the code to gdga.github.io to use the updated boomerang codebase. However it gives $injector:modulerr error when run from browser. It runs fine from local system however. Can someone help? I really don't understand the reason.

**Comment by Splaktar** [comment]
@SaptakS Do you have a link to your fork? and the deployed version with the error?

**Comment by SaptakS** [comment]
Yeah.... [Forked Version](https://github.com/GDGA/boomerang).... [Deployed Version](https://github.com/GDGA/boomerang)... The forked version works perfectly but the deplyed version shows error.

**Comment by Splaktar** [comment]
I just added steps for gh-pages hosting that might be helpful: https://github.com/gdg-x/boomerang/wiki/Host-your-chapter-website-on-GitHub-in-15-minutes

Do you have a link to the deployed application so that I can debug it?

**Comment by Splaktar** [comment]
I can see http://gdga.github.io/boomerang/ but I don't see injector errors, the Code of Conduct link doesn't seem to work though. You might want to merge in the latest upstream gh-pages.

**Comment by SaptakS** [comment]
Yeah. This fork works. But [https://gdga.github.io](https://gdga.github.io) doesn't work. This is where the injector error gets shown.

**Comment by Splaktar** [comment]
That link you gave me seems to work fine other than an `http` request on an `https` site. I've opened a PR #92 for that.

**Comment by SaptakS** [comment]
I just checked. Its working fine right now. But it wasn't when I created the issue. Not sure why because I haven't edited anything ever since. Anyways thanks.

**Comment by Splaktar** [comment]
No problem. Sometimes it takes a few minutes after a push for GitHub pages to fully update.
