### ISSUE TITLE
Add an infographic to the code of conduct

### ISSUE THREAD

**Issue by mkpartnersDev1** [gdg-x/boomerang#89]
I know it sounds silly, but there's a lot text on the screen.  A cool infographic near the top would be useful.

**Comment by tasomaniac** [comment]
I think CoC can contain lots of text. I haven't seen any CoC with graphics. Do you have an example?

**Comment by joaobiriba** [comment]
I think cool be prettier something like [this](http://blog.pgi.com/wp-content/uploads/2011/11/worksnug-code-of-conduct-1-500x353.jpg)

**Comment by SaptakS** [comment]
@joaobiriba I think that kind of design won't go with the remaining website design.

**Comment by Splaktar** [comment]
We could make some kind of infographic work, we just need an artist or designer to build something.

**Comment by tasomaniac** [comment]
Yeah but we don't have a designer with us yet. This issue can stay as is for months. 

@mkpartnersDev1 @joaobiriba do you know someone that can do this?
