### ISSUE TITLE
Site won't work properly in Mobile.

### ISSUE THREAD

**Issue by lucasxas** [gdg-x/boomerang#99]
Boomerang is not responsive to Small screens, things like the 'toolbar' and the events page look funny.

<img width="200" alt="screen shot 2016-06-21 at 7 32 04 pm" src="https://cloud.githubusercontent.com/assets/1713186/16221495/320a8f0a-37e7-11e6-8124-bec8cc9c0ff2.png"> <img width="200" alt="screen shot 2016-06-21 at 7 32 21 pm" src="https://cloud.githubusercontent.com/assets/1713186/16221528/6b05b582-37e7-11e6-9faf-6d0c5cc9501c.png">

**Comment by Splaktar** [comment]
The site is designed to be responsive and work great on phones and tablets. So we'll need some more specific information like phone brand or screen size and resolution, OS version, and browser version.

**Comment by lucasxas** [comment]
Hi @Splaktar sorry for the delay in replying this. I'm using Chrome on my Mac to debug the phone size screens. 

I just cloned master and followed the steps in the readme file to deploy the site locally.

**Comment by Splaktar** [comment]
OK, thanks. Looks like this was working fine in the previous version, there must be a regression related to Angular 1.5.6 or something. I will take a closer look when I have time. Thanks for reporting.

**Comment by lucasxas** [comment]
@Splaktar another thing to add Michael,the http://gdgspacecoast.org/ works perfectly in Mobile :)

**Comment by Splaktar** [comment]
Yeah, it isn't updated to the latest version of boomerang.
